### PR TITLE
Separate MD5 hash calculation from string and filestream/data

### PR DESCRIPTION
**Pull request by baobo5625**
I've encountered an issue that MD5 hash calculation incorrect causing the updates failed.

After debugging, I found the method used for hash calculation couldn't be applied to string calculation in my situation (listed below)

cordova version: 8.0.0
8c85908a8918:cordova bobao$ cordova platform list
Installed platforms:
  android 6.2.3
  ios 4.5.0
Available platforms: 
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

8c85908a8918:cordova bobao$ cordova plugins
code-push 2.0.5 "CodePushAcquisition"
com.wmjalak.cordova.fileopener 1.0.0 "File Opener"
cordova-plugin-alipay-v2 0.0.3 "alipay"
cordova-plugin-battery-status 1.2.2 "Battery"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-code-push 1.11.10 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-contacts 2.2.1 "Contacts"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-datetime-picker 0.5.1 "Date / Time Picker"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-device-motion 1.2.3 "Device Motion"
cordova-plugin-device-orientation 1.0.5 "Device Orientation"
cordova-plugin-dialogs 1.3.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-gctouch-id 0.0.1 "GCTouchID"
cordova-plugin-geolocation 2.4.1 "Geolocation"
cordova-plugin-globalization 1.0.5 "Globalization"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-jcore 1.1.4 "JCore"
cordova-plugin-media 2.4.1 "Media"
cordova-plugin-media-capture 1.4.1 "Capture"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-touch-id 3.2.0 "Touch ID"
cordova-plugin-vibration 2.1.3 "Vibration"
cordova-plugin-wechat 1.4.0 "Wechat"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
jpush-phonegap-plugin 3.1.7 "JPush"
phonegap-plugin-barcodescanner 6.0.5 "BarcodeScanner"

### CODE REVIEW

**Comment by alexandergoncharov** [comment]
Hi @baobo5625 ,
Thanks for contribution!

**Comment by alexandergoncharov** [comment]
Hi @baobo5625 ,

Could you please clarify what is your issue situation(you described in your comment above) and in which cases calculation incorrect?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hey @baobo5625 ,

Just a friendly ping =)

Thanks,
Alexander

**Comment by baobo5625** [comment]
Thanks Alex for reminding.

I was helping a customer to build with the code push project, and I found
the file md5 calculation was correct although once calculating for the
manifest file list, it was incorrect.

So instead of using datastream calculation, I used the string calculation,
and it turns out to be the correct one.

I believe it might due to there were Chinese character in the file name,
and causing the steaming calculation become incorrect.


Additionally, I found sometime the partial updates was unsuccessful (even
with original version), but I couldn't figure out the reason as the file
lists looks like the same as in remote server.




Regards,

Bo Bao

2018-06-29 3:54 GMT+08:00 Alexander Goncharov <notifications@github.com>:

**Comment by alexandergoncharov** [comment]
Hi @baobo5625,

I'm really sorry for this long delay. Thanks for your answer. I would like to test it. But I'll do it a bit later. It is in queue.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @baobo5625,
I'm really sorry for this really long delay.

Could you please provide some example strings or dummy project with reproducing issue as I would like to debug it?

Also, I see that you haven't signed license yet.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @baobo5625,

I'm going to close this PR for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions or provide some test string for testing.
And I'm again really sorry for my big delay.

Thanks,
Alexander

**Pull request closed without merging**
