### PR TITLE
Compatibility with cordova-ios@6.1

### LINKED ISSUE #611: iOS codeSync rollback after relaunch app
in iOS Simulator the app is updated and after its auto restarted, all of the cordova plugins no longer works and whenever I relaunch the apps rollbacked to previous version. Below is the logs and my project details

Project: plain cordova
code-push: 1.12.2
iOS: 13.4.1
WebVIew: WKWebView

Javascript:

      initialize: function () {
        document.addEventListener("resume", function () {
            codePush.sync();
        });
      },
      onDeviceReady: function () {
        codePush.sync();
      }

    app.initialize();

Config:
   ` <preference name="WKWebViewOnly" value="true" />`

Logs:
```
2020-04-24 06:23:26.371705+0800 Evenz Merchant[70524:6036478] Received Event: deviceready
2020-04-24 06:23:26.691340+0800 Evenz Merchant[70524:6036478] [CodePush] Checking for update.
2020-04-24 06:23:27.876676+0800 Evenz Merchant[70524:6036478] [CodePush] Reported status: {"status":0,"appVersion":"1.0.0","deploymentKey":"ZVGoZRrJGHxpWpTQxGUsVIbiHfJ8ZFpGaxgl9","previousLabelOrAppVersion":null,"previousDeploymentKey":null}
2020-04-24 06:23:27.964797+0800 Evenz Merchant[70524:6036478] [CodePush] An update is available. {"appVersion":"1.0.0","deploymentKey":"ZVGoZRrJGHxpWpTQxGUsVIbiHfJ8ZFpGaxgl9","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/rpSibhMndLYFULAhu2Gfp87Wju2128cec040-63f4-456f-bae0-4a7a6477f7ea","isMandatory":true,"label":"v26","packageHash":"ef5af9e09ce75e7eddf3e2c35006116c24743cda96c63cb6a9cd76f09498cc3c","packageSize":7129798,"failedInstall":false}
2020-04-24 06:23:27.965389+0800 Evenz Merchant[70524:6036478] [CodePush] Downloading update
2020-04-24 06:23:27.965842+0800 Evenz Merchant[70524:6036478] -[CDVFileTransfer download:] [Line 423] File Transfer downloading file...
2020-04-24 06:23:28.793431+0800 Evenz Merchant[70524:6036599] -[CDVFileTransferDelegate connection:didReceiveResponse:] [Line 771] Streaming to file /Users/munirishak/Library/Developer/CoreSimulator/Devices/D40EC6F8-DB3B-4B83-A550-7BA920535492/data/Containers/Data/Application/B39AA08A-0AD7-4544-9F22-6403A937B6CB/Library/NoCloud/codepush/download/update.zip
2020-04-24 06:23:33.707522+0800 Evenz Merchant[70524:6036596] File Transfer Finished with response code 200
2020-04-24 06:23:33.709184+0800 Evenz Merchant[70524:6036596] -[CDVFileTransferDelegate connectionDidFinishLoading:] [Line 637] File Transfer Download success
2020-04-24 06:23:33.714640+0800 Evenz Merchant[70524:6036478] [CodePush] Package download success: {"deploymentKey":"ZVGoZRrJGHxpWpTQxGUsVIbiHfJ8ZFpGaxgl9","label":"v26","appVersion":"1.0.0","isMandatory":true,"packageHash":"ef5af9e09ce75e7eddf3e2c35006116c24743cda96c63cb6a9cd76f09498cc3c","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/library-nosync/codepush/download/update.zip"}
2020-04-24 06:23:33.714825+0800 Evenz Merchant[70524:6036478] [CodePush] Installing update
2020-04-24 06:23:34.366113+0800 Evenz Merchant[70524:6036478] [CodePush] Applying full update
2020-04-24 06:23:34.391079+0800 Evenz Merchant[70524:6036478] [CodePush] Install succeeded.
=================================================================
Main Thread Checker: UI API called on a background thread: -[WKWebView loadFileURL:allowingReadAccessToURL:]
PID: 70524, TID: 6036596, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   Evenz Merchant                      0x0000000109d063cc -[CDVWKWebViewEngine(CodePush) loadRequest:] + 1468
5   Evenz Merchant                      0x0000000109cff792 -[CodePush loadURL:] + 130
6   Evenz Merchant                      0x0000000109cff6be -[CodePush loadPackage:] + 110
7   Evenz Merchant                      0x0000000109cfd9f7 __20-[CodePush install:]_block_invoke + 551
8   libdispatch.dylib                   0x000000010a08ef11 _dispatch_call_block_and_release + 12
9   libdispatch.dylib                   0x000000010a08fe8e _dispatch_client_callout + 8
10  libdispatch.dylib                   0x000000010a0922d8 _dispatch_queue_override_invoke + 1022
11  libdispatch.dylib                   0x000000010a0a1399 _dispatch_root_queue_drain + 351
12  libdispatch.dylib                   0x000000010a0a1ca6 _dispatch_worker_thread2 + 135
13  libsystem_pthread.dylib             0x00007fff51b386b6 _pthread_wqthread + 220
14  libsystem_pthread.dylib             0x00007fff51b37827 start_wqthread + 15
2020-04-24 06:23:34.393163+0800 Evenz Merchant[70524:6036596] [reports] Main Thread Checker: UI API called on a background thread: -[WKWebView loadFileURL:allowingReadAccessToURL:]
PID: 70524, TID: 6036596, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   Evenz Merchant                      0x0000000109d063cc -[CDVWKWebViewEngine(CodePush) loadRequest:] + 1468
5   Evenz Merchant                      0x0000000109cff792 -[CodePush loadURL:] + 130
6   Evenz Merchant                      0x0000000109cff6be -[CodePush loadPackage:] + 110
7   Evenz Merchant                      0x0000000109cfd9f7 __20-[CodePush install:]_block_invoke + 551
8   libdispatch.dylib                   0x000000010a08ef11 _dispatch_call_block_and_release + 12
9   libdispatch.dylib                   0x000000010a08fe8e _dispatch_client_callout + 8
10  libdispatch.dylib                   0x000000010a0922d8 _dispatch_queue_override_invoke + 1022
11  libdispatch.dylib                   0x000000010a0a1399 _dispatch_root_queue_drain + 351
12  libdispatch.dylib                   0x000000010a0a1ca6 _dispatch_worker_thread2 + 135
13  libsystem_pthread.dylib             0x00007fff51b386b6 _pthread_wqthread + 220
14  libsystem_pthread.dylib             0x00007fff51b37827 start_wqthread + 15
2020-04-24 06:23:34.438684+0800 Evenz Merchant[70524:6036478] IAB.close() called but it was already closed.
```

### PR DESCRIPTION
**Pull request by szh**
Fixes #611 and the final remaining issue in #624 

I'm not experienced with Objective-C so please review my code carefully!

### CODE REVIEW

**Comment by szh** [comment]
Upon further testing, I've found the following worrying issue.
I see when I load the app that `window.location` is still a `file://` url, not an `app://localhost` file as specified in the app's config.xml:
```
<preference name="scheme" value="app"/>
<preference name="hostname" value="localhost"/>
```
The `window.origin` is therefore null, which poses a problem for CORS. I configured my site to allow CORS for app://localhost but not for 'null'.
It seems like my fix only solves the issue of the content not loading, but doesn't modernize the plugin to use the new scheme that's used by Cordova with WKWebView, starting in cordova-ios v6.
So I tried using the code in 'loadPluginRequest' from 'CDVWKWebViewEngine+CodePush.m' instead of from 'loadRequest' which is what I was using. That worked for the initial load but when trying to reload the page in JavaScript with `location.reload()` I get a blank white page with no errors.
Any help from the authors? I don't really understand all of the logic going on in these functions.

PS Is this plugin still being actively maintained by Microsoft? This is a serious issue - incompatibility with the latest cordova library - and so far it seems like it's been completely left up to the community.

**Comment by szh** [comment]
> So I tried using the code in 'loadPluginRequest' from 'CDVWKWebViewEngine+CodePush.m' instead of from 'loadRequest' which is what I was using. That worked for the initial load but when trying to reload the page in JavaScript with `location.reload()` I get a blank white page with no errors.


I just committed this change. Right now it seems the reload issue might've been from a missing `<allow-navigation href="app://*"/>` tag in my config.xml. Will follow up after more thorough testing.

**Comment by szh** [comment]
I'm still running into issues with white screens. I've given this plugin everything I have (with my very limited Objective-C and iOS knowledge) but without some attention from the plugin authors this isn't a viable option for us and we're going to have to switch to another live update solution. Where is MS?

**Comment by bterres** [comment]
@szh is correct. This plugin does not work with the latest cordova-ios (6+). Cordova-ios 6+ has integrated the wkWebview engine functionality, making cordova-plugin-wkwebview-engine obsolete.

Specifically, Codepush will not work when a custom scheme and hostname is specified.  The custom scheme is required for doing CORS requests on wkWebview. Code Push DOES work with the file:// protocol, so a basic Cordova project will work with this plugin, but not one that requires hitting an external api.

To reproduce:

1. Create a new cordova project.
2. Add cordova-plugin-code-push
3. Create a Codepush project and add the deployment key to config.xml and add `codePush.sync()` to `onDeviceReady` in www/js/index.js
4. **Add custom scheme and hostname to config.xml** as @szh mentioned
```
    <preference name="scheme" value="app"/>
    <preference name="hostname" value="localhost"/>
```
5. Build the cordova project and create a Codepush release

Codepush updates will get as far as installation, but the redirect to the new release code will fail, resulting in a white screen.

**Comment by mark-divitt** [comment]
Any updates on this issue?  WKWebView is now required by Apple/iOS and Apple has released iOS 14.  CodePush (for Cordova) is effectively broken in iOS as a result.  Sure seems to me like this should be a very high priority for the CodePush team that supports Cordova.  I see no evidence of active work on this issue...

**Comment by ruslan-bikkinin** [comment]
Hi @szh @bterres @mark-divitt and thanks a lot for your effort on desire to fix this! Unfortunately, this PR doesn't cover all cases that may lead to the problems w/ cordova-ios 6 so I've prepared ultimate fix #655 that should be fixing all found problems. Please feel free to review it there. I'm closing this for now.

**Pull request closed without merging**
