### PR TITLE
WIP: refactor(file-transfer): remove fileTransfer native usage 

### PR DESCRIPTION
**Pull request by leo6104**
Related issue #446 

Related documents:
https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html

### CODE REVIEW

**Comment by alexandergoncharov** [comment]
Hi @leo6104,
Thanks for contributing!

This changes require more time for investigate and tests. Sorry for delay.

**Comment by leo6104** [comment]
@alexandergoncharov It will need more commits for tests. I will test on my services real device. After that, i will notify to you in here.

**Comment by alexandergoncharov** [comment]
@leo6104, Yeah that would be great. Thanks! I'll be waiting your results.

**Comment by alexandergoncharov** [comment]
@leo6104 , Thanks for this great work!

With this news I think that we should use `cordova-plugin-file-transfer` for now. It shouldn't create some bugs.  But I think in the future we will reopen this PR and your changes will not be lose.
For now I'm going to close this PR. Please feel free to reopen it if you have any questions or suggestions.

Thanks,
Alexander

**Comment by leo6104** [comment]
@alexandergoncharov I totally agree with you. 

Thanks for maintaining awesome repository. I hope i have a chance to contribute this awesome repository in the future :) 

Have a nice day. ^^ 
Sangmin

**Comment by alexandergoncharov** [comment]
We will be happy for your contributing :)
Thanks for being interested in the CodePush!

You too!

**Pull request closed without merging**
