### PR TITLE
fix graddle conflict

### PR DESCRIPTION
**Pull request by nitrique**
Fix bug on https://github.com/microsoft/cordova-plugin-code-push/issues/600

### CODE REVIEW

**Comment by videmort** [comment]
Works fine

**Comment by GusLAN** [comment]
works perfectly for me, thanks!

**Comment by Krasavinigor** [comment]
Hello @nitrique!
Sorry for the delay.
Thank you for contributing. You've done good and useful job=)
I reproduced error, but your fix doesn't work for me
Steps:
1) Add cordova-plugin-firebase-dynamiclinks. Changed classpath `'com.google.gms:google-services:3.3.0'` version to **4.2.0** for reproduction of this issue. For classpath `'com.google.gms:google-services:4.3.3'` all works good.
2) Add cordova-plugin-code-push
3) Run command cordova build android

[Archive.zip](https://github.com/microsoft/cordova-plugin-code-push/files/4469977/Archive.zip)

**Comment by videmort** [comment]
Hello @Krasavinigor. Adjust the Firebase plugin to upgrade to google-services 4.3.3 instead 4.2.0 and will work

The problem with the phonegap-push-plugin is fixed with that change, not necessary to do nothing more.

**Comment by Krasavinigor** [comment]
Thanks @videmort.
So, I'm going to close this PR.

**Comment by videmort** [comment]
@Krasavinigor this pr should be merged, not closed. It fixed several compile problems with a lot of cordova plugins. If you use that plugin  cordova-plugin-firebase-dynamiclink changing only the google play version will not work due nimbusds or with phonegap-push-plugin it's same.
Skip net.minidev:json-smart in gradle to compile.

Merge and create new release with that fix not closing. 
The issue  --> https://github.com/microsoft/cordova-plugin-code-push/issues/600

And the log is very very clear 

`Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2
.3.

The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
ifact with the issue.
-- Project 'app' depends onto net.minidev:json-smart@{strictly 2.3}
-- Project 'app' depends onto com.nimbusds:nimbus-jose-jwt@{strictly 5.1}
-- Project 'app' depends onto com.nimbusds:nimbus-jose-jwt@5.1`

**Comment by arturoberanlg** [comment]
+1

**Comment by arturoberanlg** [comment]
works perfectly, thanks!

**Comment by videmort** [comment]
@alexandergoncharov merge this. Bump version and create new release.

**Comment by alexandergoncharov** [comment]
Hi all,
Thanks for contributing!

@videmort , thanks for providing additional details!

We've tested it and haven't found any issues.

**Comment by dpogue** [comment]
This change causes Android apps to crash when downloading an update, due to missing classes. See #613

**Comment by ludufre** [comment]
Yeah, I have the same #613 issue, because of this changes.

With latest versions `1.13.1` I have to change `compile('com.nimbusds:nimbus-jose-jwt:5.1') { exclude group: "net.minidev", module: "json-smart" }` to `compile 'com.nimbusds:nimbus-jose-jwt:5.1'`

**Pull request merged**
